### ISSUE TITLE
Improve documentation by listing all dependencies and how to install them.

### ISSUE THREAD

**Issue by rpsene** [Unicamp-OpenPower/powergraph#1]

**Comment by Guilhermeslucas** [comment]
Dependencies right now are:
- ipmitool
- python 2.7

What else? One more question...are we writing on how to install it by package managers only?

**Comment by rpsene** [comment]
We need to look at both tools and list the Python packages as dependencies: json, csv, sys, argparse, datetime, tinydb, os, sys, time, subprocess

**Comment by Guilhermeslucas** [comment]
Right! telling people how to install it via pip is ok? I think it's the best way.

**Comment by rpsene** [comment]
For Python packages, we can create a file called requirements.txt, which can be used by pip to install it automatically. Example: sudo pip install -r ./requirements.txt

It will install all dependencies automagically :sunglasses:

**Comment by Guilhermeslucas** [comment]
Yeah, thats really the best way. I'll do it ASAP.

**Comment by Guilhermeslucas** [comment]
Just added a ```requirements.txt``` and updated the readme telling how to install the dependencies via ```pip```. The python libraries that are included on the code but not listed on the requirements file are not downloadable via pip, cause they are already installed by default.

**Comment by Guilhermeslucas** [comment]
Can we close this one?
